### ISSUE TITLE
uncaught exceptions

### ISSUE THREAD

**Issue by z1haze** [nek4life/sfcc-studio#10]
I have experienced several uncaught exception issues in the last day of using the plugin.

So far I have encountered the following uncaught exceptions:

file not found exception
no such element exception
authentication exception (even though its authenticating)

Its unclear yet as to what exactly the cause of these are, but just wanted to open an issue so you are aware there are uncaught exceptions. I will comment if I encounter more and try to give details on when/how these are happening.

**Comment by z1haze** [comment]
The FileNotFoundException seems to happen if you change branches, and the file that existed in the previous branch no longer exists in the branch you switched to.

**Comment by nek4life** [comment]
Thanks for the info! If you could create separate tickets and provide the stack traces that would be useful to help debug the issues.

**Comment by nek4life** [comment]
I'm going to go ahead and close this issue. If you get the authentication error again feel free to open up a new ticket with the stack trace so it can be debugged. Thanks!
