### ISSUE TITLE
webpack output changed files not getting uploaded

### ISSUE THREAD

**Issue by z1haze** [nek4life/sfcc-studio#11]
Carrying the discussion from another issue into a new one:

For a project I'm working on, we have webpack being used to take our input js files and output bundles and chunked js files to the static/js directory. It seems that these files are not automatically recognized as being updated by your watcher. I have had SOME luck by after the webpack bundler runs, if you click out of webstorm, and then click back into webstorm, it will trigger the commerce cloud tab to upload the changed files. I hope we can address this as it is basically not usable in this situation for me.

**Comment by z1haze** [comment]
i saw you already opened one. my bad.

**Comment by nek4life** [comment]
No problem! Thanks for letting me know!
