### ISSUE TITLE
update for latest version of webstorm

### ISSUE THREAD

**Issue by z1haze** [nek4life/sfcc-studio#15]
Can you please make this update for the latest version of the IDE. I updated today and no more plugin :(

WebStorm 2019.1
Build #WS-191.6183.63, built on March 21, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by nek4life** [comment]
I have an EAP channel release. I'll publish this to the main repo now that 2019.1 has been updated.

Here's the EAP release download link in the meantime. Just select the EAP tab and download. I believe that should work.

https://plugins.jetbrains.com/plugin/11590-salesforce-commerce-cloud-studio

**Comment by nek4life** [comment]
I published the updated plugin. It will be available through the regular release channel as soon as it is approved by JetBrains.

**Comment by z1haze** [comment]
Beautiful. Nice work. Anything new or just a version bump?

Sent from Mail for Windows 10

**Comment by nek4life** [comment]
**New Features**
- Compatibility with 2019.1 IDE releases
- Static mapping of form.xsd for form field auto completion
- Now deletes files properly from the server with also fixed deleted files issue
- Moved HTTP client instantiation to getter to prevent settings not being updated without restarting IDE

**Comment by nek4life** [comment]
This has now been published to the repo
