### ISSUE TITLE
Rename file

### ISSUE THREAD

**Issue by AVATOR** [nek4life/sfcc-studio#16]
Hi.
After rename file plugin created a file with a new name on the server but does not delete the file with an old name.

**Comment by nek4life** [comment]
Hmm not sure how I could track this one. I might have to dig into the API a bit further to see if the VFS has statuses I could use in order to accomplish this.

**Comment by nek4life** [comment]
Hey @AVATOR I believe I'm sending deletes to the server as well. Can you confirm whether this is still and issue with the latest version of the plugin on 2019.2?

That version also has your contributions! Thanks :D

**Comment by nek4life** [comment]
Haven't heard back. If this is still an issue please reopen. Thanks!
