### ISSUE TITLE
Upload broken if empty cartridge directory

### ISSUE THREAD

**Issue by jonathansayag** [nek4life/sfcc-studio#19]
Hi,

When you are using the command `Commerce Cloud > Clean Cartridges`, if you have an empty cartridge folder, the result is :

- The job is broken
- You code version on BM is removed
- Upload is not done

Best

**Comment by nek4life** [comment]
Hi @jonathansayag can you provide the actual folder structure. Also if there is a stacktrace that would be helpful as well.

I'm also curious why you have an empty cartridge added to the cartridge settings.
