### ISSUE TITLE
Idea 2019.3 

### ISSUE THREAD

**Issue by AVATOR** [nek4life/sfcc-studio#21]
The plugin does not work on the IntelliJ IDEA 2019.3 Build #IU-193.5233.102

**Comment by nek4life** [comment]
Hey @AVATOR you should be able to build the develop branch and get it running. I'll take a look tomorrow at submitting the plugin to the plugin repository.

**Comment by nek4life** [comment]
The update is pending approval. Hopefully it will be approved soon.

**Comment by AVATOR** [comment]
Thanks!
