### ISSUE TITLE
isml fragments showing errors

### ISSUE THREAD

**Issue by z1haze** [nek4life/sfcc-studio#6]
Is there anything you can do to the the isml language injection fragments always being underlined like there is something wrong? Example here:
![image](https://user-images.githubusercontent.com/6024725/52582833-222e9f00-2dfc-11e9-96d3-8adf0cec4602.png)

**Comment by nek4life** [comment]
I've managed to fix the issue out side of the plugin by disabling the two inspections that are causing the underlines. If you place your cursor on the underlined text and click the light bulb that shows up you can disable that particular inspection for the project and that fixes the issue.

You have two inspections causing issues here. The first is the JS expressions and the second is self closing html elements. I've disabled both of those and it makes a huge difference.

If you like to see if there is a way to fix this at the plugin level the script is being injected here.

https://github.com/nek4life/sfcc-studio/blob/master/src/main/java/com/binarysushi/studio/language/isml/ISMLScriptInjector.java#L32

And the ISML tags are added in the file below. There may be a way to mark them as self closing somehow.

https://github.com/nek4life/sfcc-studio/blob/master/src/main/java/com/binarysushi/studio/language/isml/codeInsight/tags/ISMLTagDescriptor.java

**Comment by z1haze** [comment]
I found the empty tags one.. which section is the js expressions? in the javascript section i didnt see it, nor in the html one

**Comment by z1haze** [comment]
found it!
