### ISSUE TITLE
Add Script Debugger

### ISSUE THREAD

**Issue by nek4life** [nek4life/sfcc-studio#9]
Since I know this is likely to be requested I'm going to create an issue for it. That being said I've started looking into this and it's going to be slow going on the intellij integration side of things. The [SDAPI](https://documentation.b2c.commercecloud.salesforce.com/DOC1/topic/com.demandware.dochelp/ScriptDebuggerAPI/latest/usage/ScriptDebuggerAPI.html?cp=0_13) looks pretty straightforward, however there aren't a lot of clear instructions on how to integrate this into the Intellij platform.

I currently have the following question open with not much help so far.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/360002856819-How-to-get-started-writing-a-custom-js-like-language-script-debugger-

And I also have been told that I may want to use the scriptDebugger built into Intellij as a base, but with no instructions on how to extend or modify it.

https://github.com/JetBrains/intellij-community/tree/master/platform/script-debugger 

I'll try to keep this issue update with any information I can come up with in order to get something working, but please know this isn't likely to happen very quickly. Though it would be an amazing feature to have for sure.

**Comment by nek4life** [comment]
Thanks @ulitink I had been doing a bit of research and I believe you are right that xdebugger would be the way to go.

Here is a good example of how to use the xdebugger in action. 

https://github.com/mulesoft-labs/data-weave-intellij-plugin/tree/master/data-weave-plugin/src/main/java/org/mule/tooling/lang/dw/debug 

I don't remember seeing the documentation or do you just mean the documentation in the source code itself?

I think the next steps are to write an API client for the SDAPI. Then I think it's as "easy" as extending and hooking up all the right classes... I started writing one in Kotlin, but then ran into an issue trying to get kotlinx.serialization working within the IDE. It worked fine as a separate library. Not sure what I was doing wrong. 

(Never used Kotlin before and wanted to try it out. I wonder if I'd get more contributions if I continue to use Java or if I started using Kotlin for everything)

I'll take a look at those classes you suggest as well! Thanks for the help!

**Comment by xpuctto** [comment]
Hi @nek4life ,

Is there any progress on the debugger, since that's the only reason I haven't started using IntelliJ as my main SFCC IDE?

**Comment by nek4life** [comment]
Hi @xpuctto there is progress, but it's slow going.

What I have so far is on this branch https://github.com/nek4life/sfcc-studio/tree/debugger I'm able to start and stop the debugger, but the SDAPI needs to be wired into the xdebugger event handlers.

It's mainly figuring out how to extend the IDE and to do that there's a lot of reading other plugins and diving into the class implementations.

**Comment by nek4life** [comment]
Initial version will be in the next release once it is approved by JetBrains

**Comment by SangilYun** [comment]
Hi, how do I use the debugger?
